apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  labels:
    prometheus: dev
spec:
  selector:
    matchLabels:
      grafana: dev
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http