apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
data:
  WAL_S3_BUCKET: "postgres-operator"
#  WAL_BUCKET_SCOPE_PREFIX: ""
#  WAL_BUCKET_SCOPE_SUFFIX: ""
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: '00 10 * * *'
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "password"
  AWS_S3_FORCE_PATH_STYLE: "true" # needed for MinIO
  AWS_ENDPOINT: "https://s3.danielr1996.de"
  AWS_REGION: "nbg"
  WALG_DISABLE_S3_SSE: "true"
  BACKUP_NUM_TO_RETAIN: "5"
  CLONE_USE_WALG_RESTORE: "true"
#  PGUSER: "postgres"
#  DEBUG: "false"
#  BACKUP_SCHEDULE: "*/30 * * * *" # Every 30 minutes
#  CLONE_METHOD: "CLONE_WITH_WALE"
#
#  AWS_ENDPOINT: "https://s3.eu-central-003.backblazeb2.com"
#  CLONE_AWS_ENDPOINT: "https://s3.eu-central-003.backblazeb2.com"
#
#  WAL_S3_BUCKET: "danielrichtercodes-postgres-backup"
#  CLONE_WAL_S3_BUCKET: "danielrichtercodes-postgres-backup"
#
#  AWS_ACCESS_KEY_ID: "0031b5051e71cf20000000005"
#  CLONE_AWS_ACCESS_KEY_ID: "0031b5051e71cf20000000005"
#
#  AWS_SECRET_ACCESS_KEY: "K0039h2cQV0l/42EG4ucwuUkPe8NiO8"
#  CLONE_AWS_SECRET_ACCESS_KEY: "K0039h2cQV0l/42EG4ucwuUkPe8NiO8"
#
#  AWS_S3_FORCE_PATH_STYLE: "true"
#  CLONE_AWS_S3_FORCE_PATH_STYLE: "true"
#
#  USE_WALG_BACKUP: "true"
#  CLONE_USE_WALG_RESTORE: "true"
#
