apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
