apiVersion: v1
kind: Service
metadata:
  name: restic-exporter
  namespace: restic-exporter
  labels:
    app: restic-exporter
spec:
  selector:
    app: restic-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: metrics