apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: attach-pullsecret-to-pods
spec:
  rules:
    - name: add-imagepullsecret-to-pod
      match:
        any:
          - resources:
              kinds: ["Pod"]
      mutate:
        patchStrategicMerge:
          spec:
            imagePullSecrets:
              - name: image-pull-secret