apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{
    dict "auths" (
      dict .Values.modules.imagePullSecret.registry (
        dict
          "username" .Values.modules.imagePullSecret.username
          "password" .Values.modules.imagePullSecret.password
          "email" .Values.modules.imagePullSecret.email
          "auth" (
            printf "%s:%s"
              .Values.modules.imagePullSecret.username
              .Values.modules.imagePullSecret.password
            | b64enc
          )
      )
    )
    | toJson
    | b64enc
  }}
