{{- range $pool := .Values.bgp.pools }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $pool.name | quote }}
  namespace: metallb-system
spec:
  avoidBuggyIPs: true
  autoAssign: {{ default false $pool.autoAssign }}
  addresses:
    {{- range $addr := $pool.addresses }}
    - {{ $addr | quote }}
    {{- end }}
---
{{- end }}
