bgp:
  peerings:
    - name: vyos
      myASN: 64522
      peerASN: 64520
      addresses:
        - 192.168.178.1
        - fd00::1
  pools:
    - name: static
      addresses:
        - 192.168.210.0/24
        - fd00:69:1::/64
    - name: dynamic
      autoAssign: true
      addresses:
        - 192.168.212.0/24
        - fd00:69:8f3a::/64