apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{- if .Values.prefix }}{{ .Values.prefix }}-{{ end }}gfs-daily
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    ttl: 336h
{{ include "velero.schedule.policy.pv-pvc" . | indent 4 }}
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{- if .Values.prefix }}{{ .Values.prefix }}-{{ end }}gfs-weekly
  namespace: velero
spec:
  schedule: "0 3 * * 0"
  template:
    ttl: 1344h
{{ include "velero.schedule.policy.pv-pvc" . | indent 4 }}
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{- if .Values.prefix }}{{ .Values.prefix }}-{{ end }}gfs-monthly
  namespace: velero
spec:
  schedule: "0 4 1 * *"
  template:
    ttl: 8760h
{{ include "velero.schedule.policy.pv-pvc" . | indent 4 }}
